config/routes.rb
Rails.application.routes.draw do
    root 'homes#top'
    get "home/about" => "homes#about"
    get "search" => "users#search"

    devise_for :users
    resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
        resource :favorites, only: [:create, :destroy]
        resources :book_comments, only: [:create, :destroy]
    end
    resources :users, only: [:new, :create, :index, :show, :edit, :update]

    resources :users do
    member do
     get :followings, :followers
    end
    end

    resources :relationships, only: [:create, :destroy]
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true
    validates :body, length: { maximum: 200 }
    
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :book_comments, dependent: :destroy

    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
    attachment :profile_image 


    def Book.search(search, user_or_book, how_search)
        if how_search == "1"
            Book.where(['title LIKE ?', "%#{search}%"])
        elsif how_search == "2"
            Book.where(['title LIKE ?', "%#{search}"])
        elsif how_search == "3"
            Book.where(['title LIKE ?', "#{search}%"])
        elsif how_search == "4"
            Book.where(['title LIKE ?', "#{search}"])
        else
            Book.all
        end
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!
before_action :ensure_correct_user, only:[:edit, :update]


  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have created book successfully.'
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = current_user
    @book_comment = BookComment.new
    @book_comments = BookComment.all
  end

  def edit
  end

  def update
    if @book.update(book_params)
    redirect_to book_path(@book), notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      redirect_to books_path
    end
  end


  private
    def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
    end

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
<h1>New Book</h1>
<% if book.errors.any? %>
  <%= book.errors.count %>件のエラーが発生しました
  <% book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<%= form_with model: book, local:true do |f| %>
  <h4>title</h4>
  <%= f.text_field :Title %>
  <h4>opinion</h4>
  <%= f.text_area :Body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/_list1.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, size: '100x100', fallback: "no_image.jpg" %>
<table class='table'>
    <tbody>
        <tr></tr>
        <tr>
            <th>name</th>
            <th><%= user.name %></th>
        </tr>
        <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
        </tr>
        <tr>
            <th>Follows</th>
            <td><%= link_to "#{user.followings.count}", followings_user_path(user.id) %></td>
            <th></th>
        </tr>
        <tr>
            <th>Followers</th>
            <td><%= link_to user.followers.count, followers_user_path(user.id) %></td>
            <th></th>
        </tr>
    </tbody>
</table>


<%= render "relationships/follow_button", user: user %>
</br>
<%= link_to "", edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog"%>

app/views/books/_list2.html.erb
<h2>New book</h2>
<% if book.errors.any? %>
  <div id="error_explanation">
    <h2><%= book.errors.count %> error prohibited this product from being saved:</h2>
    <% book.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  </div>
<% end %>


<%= form_with model: book, local:true do |f| %>
  <div class="form-group">
    <label for="book_title">Title</label>
    <input class="form-control book_title" type="text" name="book[title]" id="book_title">
  </div>

  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <textarea class="form-control book_body" name="book[body]" id="book_body"></textarea>
  </div>

  <div class="form-group">
    <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
  </div>
<% end %>

app/views/books/edit.html.erb
<%# ここからエラーメッセージ %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= @book.errors.count %> error prohibited this product from being saved:</h2>

      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%# ここまでエラーメッセージ %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Editing Book</h2>
        <%= form_with model:@book, local:true do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
              <%= f.text_field :title, class: "form-control" %>
          </div>
  
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
              <%= f.text_area :body, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.submit "Update Book", class: "btn btn-success" %>
          </div>
        <% end %>

        <%= link_to "Show", book_path(@book) %>
         |
        <%= link_to "Back", books_path %>
    </div>
  </div>

app/views/books/index.html.erb
<p id="notice"><%=  notice %></p>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/list1', user:current_user %>
      <%= render 'books/list2', book:@book %>
    </div>
    <div class="col-md-8 offset-md-1">
<%# ここからエラーメッセージ %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= @book.errors.count %> error prohibited this product from being saved:</h2>

      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%# ここまでエラーメッセージ %>
      <h1>Books</h1>

      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th class='table-name'>Title</th>
            <th class='table-name'>Opinion</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to user_path(book.user) do %>
              <%= attachment_image_tag book.user, :profile_image, size: "100x100", fallback: "no_image.jpg" %><% end %></td>
              <td><%= link_to book.title, "/books/#{book.id}" %></td>
              <td><%= book.body %></td>
              <td class="favorite-btn<%= book.id %>">
                <%= render 'favorites/favorite', book: book %>
              </td>
              <td>  <p><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></p></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<%= render 'books/list1', user:@user %>
<%= render 'books/list2', book:@book %>

app/views/books/show.html.erb
<p id="notice"><%=  notice %></p>
<div class="container">
    <div class="row">
        <div class="col-md-3">

          <%= render 'books/list1', user:@book.user %>
          <%= render 'books/list2', book:@newbook %>

        </div>
        <div class="col-md-8 offset-md-1">
          <h2>Book detail</h2>

            <table class="table">
              <tr>
                <td><%= link_to user_path(@book.user) do%>
                    <%= attachment_image_tag @book.user, :profile_image, size: "100x100", fallback: "no_image.jpg" %><% end %></br>
                    <%= link_to @book.user.name, user_path(@book.user) %>
                </td>
                <td><%= link_to @book.title %>
                </td>
                <td><%= @book.body %>
                </td>
                <td class="favorite-btn<%= @book.id %>">
                <%= render 'favorites/favorite', book: @book %>
                </td>
            

                <% if @book.user == current_user %>
                <td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %>
                </td>
                <td><%= link_to "Destroy", book_path(@book), method: :delete, class: "btn btn-sm btn-danger", data: { confirm: 'Are you sure?' }  %>
                </td>
                <% end %>
              </tr>
            </table>
            <div class="comments_<%= @book.id %>">
              <%= render 'book_comments/comments', book: @book, book_comment: @book_comment %>
            </div>


        </div>
    </div>
</div>